laravel/routes/web.php
<?php

use App\Http\Controllers\ConsultaController;
use App\Http\Controllers\PoliticaDePrivacidadeController;
use App\Http\Controllers\Profissionais\Auth\AuthController;
use App\Http\Controllers\Profissionais\Auth\PasswordController;
use App\Http\Controllers\Profissionais\CertificadosController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect()->route('consulta.index');
})->name('home');

Route::get('/consulta', [ConsultaController::class, 'index'])->name('consulta.index');
Route::get('/consulta/{hash_id}', [ConsultaController::class, 'show'])->name('consulta.show');
Route::get('/consulta/{hash_id}/print', [ConsultaController::class, 'showPrint'])->name('consulta.showPrint');
Route::post('/consulta', [ConsultaController::class, 'post'])->name('consulta.post');
Route::get('politica-de-privacidade', [PoliticaDePrivacidadeController::class, 'index'])->name('politica-de-privacidade');
Route::post('aceite-de-cookies', [ConsultaController::class, 'postCookies'])->name('aceite-de-cookies.post');

Route::name('profissionais.')->group(function () {
    Route::get('/cadastro', [AuthController::class, 'indexCadastro'])->name('cadastro');
    Route::post('/cadastro', [AuthController::class, 'cadastro'])->name('cadastro.post');
    Route::get('/login', [AuthController::class, 'index'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.post');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/esqueci-a-senha', [PasswordController::class, 'index'])->name('esqueci-a-senha');
    Route::post('/esqueci-a-senha', [PasswordController::class, 'post'])->name('esqueci-a-senha.post');
    Route::get('/redefinir-senha/{token}', [PasswordController::class, 'indexReset'])->name('redefinir-senha');
    Route::post('/redefinir-senha', [PasswordController::class, 'postReset'])->name('redefinir-senha.post');

    Route::group([
        'middleware' => ['auth.profissionais'],
        'guest' => ['guest.profissionais']
    ], function () {
        Route::get('/{aluno:id}/editar-cadastro', [AuthController::class, 'edit'])->name('edit');
        Route::post('/{aluno:id}/editar-cadastro', [AuthController::class, 'update'])->name('update');

        Route::get('/certificados', [CertificadosController::class, 'index'])->name('certificados');
        Route::get('/certificados/{certificado:hash_id}', [CertificadosController::class, 'show'])->name('certificados.show');
        Route::get('/certificados/{certificado:hash_id}/print', [CertificadosController::class, 'showPrint'])->name('certificados.showPrint');
    });
});


require __DIR__ . '/auth-admin.php';
require __DIR__ . '/auth-painel.php';

laravel/app/Http/Controllers/Profissionais/CertificadosController.php
<?php

namespace App\Http\Controllers\Profissionais;

use App\Http\Controllers\Controller;
use App\Models\AlunoCertificado;
use App\Models\AreaAdmin;
use App\Models\Certificado;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CertificadosController extends Controller
{
    public function index()
    {
        $aluno = Auth::guard('profissionais')->user();

        $tempoVencimento = AreaAdmin::first()->tempo_aviso_vencimento;
        $dataAtual = date('Y-m-d');
        $dataAvisoVencimento = date('Y-m-d', strtotime("+6 months", strtotime($dataAtual)));

        $certificadosValidos = Certificado::join('alunos_certificados', 'alunos_certificados.certificado_id', '=', 'certificados.id')
            ->join('alunos', 'alunos.id', '=', 'alunos_certificados.aluno_id')
            ->join('cursos', 'cursos.id', '=', 'certificados.curso_id')
            ->select('alunos_certificados.hash_id as ac_hash_id', 'cursos.titulo as curso', 'certificados.hash_id')
            ->where('alunos.id', $aluno->id)
            ->where('alunos_certificados.certificado_emitido', 1)
            ->where('certificados.data_validade', '>', $dataAvisoVencimento)
            ->orderBy('certificados.data_emissao', 'desc')
            ->get();

        $certificadosRenovacao = Certificado::join('alunos_certificados', 'alunos_certificados.certificado_id', '=', 'certificados.id')
            ->join('alunos', 'alunos.id', '=', 'alunos_certificados.aluno_id')
            ->join('cursos', 'cursos.id', '=', 'certificados.curso_id')
            ->select('alunos_certificados.hash_id as ac_hash_id', 'cursos.titulo as curso', 'certificados.hash_id')
            ->where('alunos.id', $aluno->id)
            ->where('alunos_certificados.certificado_emitido', 1)
            ->whereBetween('certificados.data_validade', [$dataAtual, $dataAvisoVencimento])
            ->orderBy('certificados.data_emissao', 'desc')
            ->get();

        $certificadosVencidos = Certificado::join('alunos_certificados', 'alunos_certificados.certificado_id', '=', 'certificados.id')
            ->join('alunos', 'alunos.id', '=', 'alunos_certificados.aluno_id')
            ->join('cursos', 'cursos.id', '=', 'certificados.curso_id')
            ->select('alunos_certificados.hash_id as ac_hash_id', 'cursos.titulo as curso', 'certificados.hash_id')
            ->where('alunos.id', $aluno->id)
            ->where('alunos_certificados.certificado_emitido', 1)
            ->where('certificados.data_validade', '<=', $dataAtual)
            ->orderBy('certificados.data_emissao', 'desc')
            ->get();


        return view('profissionais.certificados', compact('certificadosValidos', 'certificadosRenovacao', 'certificadosVencidos'));
    }

    public function show(Certificado $certificado)
    {
        $aluno = Auth::guard('profissionais')->user();

        $alunoCertificado = AlunoCertificado::join('certificados', 'certificados.id', '=', 'alunos_certificados.certificado_id')
            ->join('alunos', 'alunos.id', '=', 'alunos_certificados.aluno_id')
            ->join('cursos', 'cursos.id', '=', 'certificados.curso_id')
            ->join('instrutores', 'instrutores.id', '=', 'certificados.instrutor_id')
            ->join('instituicoes', 'instituicoes.id', '=', 'certificados.instituicao_id')
            ->select('alunos.nome as aluno_nome', 'certificados.hash_id', 'certificados.data_emissao', 'certificados.data_validade', 'certificados.cidade', 'certificados.uf', 'alunos_certificados.hash_id as ac_hash_id', 'cursos.titulo as curso_titulo', 'cursos.imagem as curso_imagem', 'instrutores.nome as instrutor_nome', 'instrutores.hash_id as instrutor_id', 'instituicoes.nome as instituicao_nome', 'alunos_certificados.qr_code')
            ->where('alunos_certificados.certificado_id', $certificado->id)
            ->where('alunos_certificados.aluno_id', $aluno->id)
            ->where('alunos_certificados.certificado_emitido', 1)
            ->first();

        return view('profissionais.certificados-show', compact('alunoCertificado'));
    }

    public function showPrint($hash_id)
    {
        $aluno = Auth::guard('profissionais')->user();

        $certificado = AlunoCertificado::join('certificados', 'certificados.id', '=', 'alunos_certificados.certificado_id')
            ->join('alunos', 'alunos.id', '=', 'alunos_certificados.aluno_id')
            ->join('cursos', 'cursos.id', '=', 'certificados.curso_id')
            ->join('instrutores', 'instrutores.id', '=', 'certificados.instrutor_id')
            ->join('instituicoes', 'instituicoes.id', '=', 'certificados.instituicao_id')
            ->select('alunos.nome as aluno_nome', 'certificados.hash_id', 'certificados.data_emissao', 'certificados.data_validade', 'certificados.cidade', 'certificados.uf', 'alunos_certificados.hash_id as ac_hash_id', 'cursos.titulo as curso_titulo', 'cursos.imagem as curso_imagem', 'instrutores.nome as instrutor_nome', 'instrutores.hash_id as instrutor_id', 'instituicoes.nome as instituicao_nome', 'alunos_certificados.qr_code')
            ->where('alunos_certificados.hash_id', $hash_id)
            ->where('alunos_certificados.aluno_id', $aluno->id)
            ->where('alunos_certificados.certificado_emitido', 1)
            ->first();

        if ($certificado->data_validade > date('Y-m-d')) {
            return view('profissionais.certificado-valido', compact('certificado'));
        }
        if ($certificado->data_validade <= date('Y-m-d')) {
            return view('profissionais.certificado-vencido', compact('certificado'));
        }
    }
}

laravel/resources/views/profissionais/certificados-show.blade.php
@extends('layouts.template')

@section('content')

<main class="login">

    <div class="externa">

        <div class="imagem">
            <div class="img"></div>
            <div class="menus">
                <p>Olá {{ auth('profissionais')->user()->nome }}!  <a href="{{ route('profissionais.edit', auth('profissionais')->user()->id) }}">[ALTERAR SENHA]  </a></p>
                <form action="{{ route('profissionais.logout') }}" method="post" class="wrapper">
                    {!! csrf_field() !!}
                    <button type="submit">SAIR<img src="{{ asset('assets/img/layout/x-sair.svg')}}" alt=""></button>
                </form>
            </div>
        </div>

        <div class="father print-certificado">
            <h1>Sistema E-cards SBC</h1>

            @if($alunoCertificado->data_validade > date('Y-m-d'))
            <div class="show">
                <h3>SEU CERTIFICADO ESTÁ ATIVO.</h3>
                <div class="certified">
                    <div class="detail_blue"></div>
                    <div class="imgs">
                        <img src="{{ asset('assets/img/layout/marca-SBC-selo.svg')}}" alt="">
                        <img src="{{ asset('assets/img/cursos/'.$alunoCertificado->curso_imagem) }}">
                    </div>
                    <div class="infos">
                        <p class="nome">{{ $alunoCertificado->aluno_nome }}</p>
                        <p class="subtrace">concluiu com êxito o curso, currículo e as avaliações propostas para o treinamento:</p>
                        <p class="curso">{{ $alunoCertificado->curso_titulo }}</p>
                    </div>
                    <div class="cert_rodape">
                        <div class="QRCODE">
                            <img src="{{ asset('assets/img/qr-code/'.$alunoCertificado->qr_code) }}">
                        </div>
                        <div class="veracidade">
                            <div class="val">
                                <div class="box_1">
                                    <p class="label">DATA DE EMISSÃO:</p>
                                    <p class="date">{{ strftime("%d %h %Y", strtotime($alunoCertificado->data_emissao)) }}</p>
                                </div>
                                <div class="box_2">
                                    <p class="label">VALIDO ATÉ:</p>
                                    <p class="date">{{ strftime("%d %h %Y", strtotime($alunoCertificado->data_validade)) }}</p>
                                </div>
                                <div class="box_2">
                                    <p class="label">CÓDIGO DESTE CERTIFICADO:</p>
                                    <p class="date">{{ $alunoCertificado->ac_hash_id }}</p>
                                </div>
                            </div>
                            <p class="consulte">Consulte a veracidade e validade deste documento lendo este QR Code, ou acesse: <a href="https://ecards.cardiol.br">https://ecards.cardiol.br</a> e informe o código do certificado.</p>

                        </div>
                    </div>
                </div>

                <div class="certified">
                    <div class="detail_blue"></div>
                    <div class="imgs">
                        <img src="{{ asset('assets/img/layout/marca-SBC-selo.svg')}}" alt="">
                        <img src="{{ asset('assets/img/cursos/'.$alunoCertificado->curso_imagem) }}">
                    </div>
                    <div class="body">
                        <div class="release">
                            <p>© {{ date('Y') }} Sociedade Brasileira de Cardiologia</p>
                        </div>
                        <div class="table">
                            <div class="box_3">
                                <P class="label">CURSO</P>
                                <p class="text">{{ $alunoCertificado->curso_titulo }}</p>
                            </div>
                            <div class="box_3">
                                <P class="label">DIRETOR DO CURSO</P>
                                <p class="text">{{ $alunoCertificado->instrutor_id }} | {{ $alunoCertificado->instrutor_nome }}</p>
                            </div>
                            <div class="box_3">
                                <P class="label">CENTRO DE TREINAMENTO</P>
                                <p class="text">{{ $alunoCertificado->instituicao_nome }}</p>
                            </div>
                            <div class="box_3">
                                <P class="label">LOCAL</P>
                                <p class="text">{{ $alunoCertificado->cidade }}, {{ $alunoCertificado->uf }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="buttons">
                    <a href="{{ route('profissionais.certificados.showPrint', $alunoCertificado->ac_hash_id) }}" target="_blank" class="btn-print-certificado">
                        <div class="print">
                            IMPRIMIR
                        </div>
                    </a>

                    <a href="{{ route('profissionais.certificados') }}">
                        <div class="button_voltar">
                            VOLTAR
                        </div>
                    </a>
                </div>
            </div>
            @endif

            @if($alunoCertificado->data_validade <= date('Y-m-d')) <div class="show">
                <h3 class="vinho">SEU CERTIFICADO ESTÁ VENCIDO.</h3>
                <div class="certified">
                    <div class="bg-vencido"></div>
                    <div class="detail_vinho"></div>
                    <div class="imgs">
                        <img src="{{ asset('assets/img/layout/marca-SBC-selo.svg')}}" alt="">
                        <img src="{{ asset('assets/img/cursos/'.$alunoCertificado->curso_imagem) }}">
                    </div>
                    <div class="infos">
                        <p class="nome">{{ $alunoCertificado->aluno_nome }}</p>
                        <p class="subtrace">concluiu com êxito o curso, currículo e as avaliações propostas para o treinamento:</p>
                        <p class="curso">{{ $alunoCertificado->curso_titulo }}</p>
                    </div>
                    <div class="cert_rodape">
                        <div class="QRCODE">
                            <img src="{{ asset('assets/img/qr-code/'.$alunoCertificado->qr_code) }}">
                        </div>
                        <div class="veracidade">
                            <div class="val">
                                <div class="box_1">
                                    <p class="label">DATA DE EMISSÃO:</p>
                                    <p class="date">{{ strftime("%d %h %Y", strtotime($alunoCertificado->data_emissao)) }}</p>
                                </div>
                                <div class="box_2">
                                    <p class="label">VALIDO ATÉ:</p>
                                    <p class="date">{{ strftime("%d %h %Y", strtotime($alunoCertificado->data_validade)) }}</p>
                                </div>
                                <div class="box_2">
                                    <p class="label">CÓDIGO DESTE CERTIFICADO:</p>
                                    <p class="date">{{ $alunoCertificado->ac_hash_id }}</p>
                                </div>
                            </div>
                            <p class="consulte">Consulte a veracidade e validade deste documento lendo este QR Code, ou acesse: <a href="https://ecards.cardiol.br">https://ecards.cardiol.br</a> e informe o código do certificado.</p>

                        </div>
                    </div>
                </div>

                <div class="certified">
                    <div class="bg-vencido"></div>
                    <div class="detail_vinho"></div>
                    <div class="imgs">
                        <img src="{{ asset('assets/img/layout/marca-SBC-selo.svg')}}" alt="">
                        <img src="{{ asset('assets/img/cursos/'.$alunoCertificado->curso_imagem) }}">
                    </div>
                    <div class="body">
                        <div class="release">
                            <p>© {{ date('Y') }} Sociedade Brasileira de Cardiologia</p>
                        </div>
                        <div class="table">
                            <div class="box_3">
                                <P class="label">CURSO</P>
                                <p class="text">{{ $alunoCertificado->curso_titulo }}</p>
                            </div>
                            <div class="box_3">
                                <P class="label">DIRETOR DO CURSO</P>
                                <p class="text">{{ $alunoCertificado->instrutor_id }} | {{ $alunoCertificado->instrutor_nome }}</p>
                            </div>
                            <div class="box_3">
                                <P class="label">CENTRO DE TREINAMENTO</P>
                                <p class="text">{{ $alunoCertificado->instituicao_nome }}</p>
                            </div>
                            <div class="box_3">
                                <P class="label">LOCAL</P>
                                <p class="text">{{ $alunoCertificado->cidade }}, {{ $alunoCertificado->uf }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="buttons">
                    <a href="{{ route('profissionais.certificados.showPrint', $alunoCertificado->ac_hash_id) }}" target="_blank" class="btn-print-certificado">
                        <div class="print">
                            IMPRIMIR
                        </div>
                    </a>

                    <a href="{{ route('profissionais.certificados') }}">
                        <div class="button_voltar">
                            VOLTAR
                        </div>
                    </a>
                </div>
        </div>
        @endif
    </div>
    </div>

    </section>


    @endsection

laravel/resources/views/profissionais/certificados.blade.php
@extends('layouts.template')

@section('content')

<main class="login">

    <div class="externa">

        <div class="imagem">
            <div class="img"></div>
            <div class="menus">
                <p>Olá {{ auth('profissionais')->user()->nome }}!  <a href="{{ route('profissionais.edit', auth('profissionais')->user()->id) }}">[ALTERAR SENHA]  </a></p>
                <form action="{{ route('profissionais.logout') }}" method="post" class="wrapper">
                    {!! csrf_field() !!}
                    <button type="submit" class="anchor_sair_menu">SAIR<img src="{{ asset('assets/img/layout/x-sair.svg')}}" class="sair" alt=""></button>
                </form>
            </div>
        </div>

        <div class="father">
            <h1>Sistema E-cards SBC</h1>

            @if(count($certificadosValidos) > 0)
            <div class="card">
                <div class="header">
                    <h2>CERTIFICADOS EMITIDOS VÁLIDOS:</h2>
                </div>
                <div class="body">
                    <div class="wrapper">
                        <div class="hr"></div>

                        @foreach($certificadosValidos as $certificado)
                        <a href="{{ route('profissionais.certificados.show', $certificado->hash_id) }}">
                            <div class="line">
                                <p class="reg">{{ $certificado->ac_hash_id }}</p>
                                <p class="desc">{{ $certificado->curso }}</p>
                                <img src="{{ asset('assets/img/layout/ico-cadastroaluno.svg')}}" alt="">
                            </div>
                        </a>
                        <div class="hr2"></div>
                        @endforeach
                    </div>
                </div>
            </div>
            @endif

            @if(count($certificadosRenovacao) > 0)
            <div class="card">
                <div class="header blue">
                    <h2>CERTIFICADOS EMITIDOS EM PERÍODO DE RENOVAÇÃO:</h2>
                </div>
                <div class="body">
                    <div class="wrapper">
                        <div class="hr2"></div>

                        @foreach($certificadosRenovacao as $certificado)
                        <a href="{{ route('profissionais.certificados.show', $certificado->hash_id) }}">
                            <div class="line">
                                <p class="reg">{{ $certificado->ac_hash_id }}</p>
                                <p class="desc">{{ $certificado->curso }}</p>
                                <img src="{{ asset('assets/img/layout/ico-enviar-email-azul.svg')}}" alt="">
                            </div>
                        </a>
                        <div class="hr2"></div>
                        @endforeach
                    </div>
                </div>
            </div>
            @endif

            @if(count($certificadosVencidos) > 0)
            <div class="card">
                <div class="header vinho">
                    <h2>CERTIFICADOS VENCIDOS:</h2>
                </div>
                <div class="body">
                    <div class="wrapper">
                        <div class="hr2"></div>

                        @foreach($certificadosVencidos as $certificado)
                        <a href="{{ route('profissionais.certificados.show', $certificado->hash_id) }}">
                            <div class="line">
                                <p class="reg">{{ $certificado->ac_hash_id }}</p>
                                <p class="desc">{{ $certificado->curso }}</p>
                                <img src="{{ asset('assets/img/layout/ico-enviar-email-azul.svg')}}" alt="">
                            </div>
                        </a>
                        <div class="hr2"></div>
                        @endforeach
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>

    </section>


    @endsection